// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqentfqncirduvhherng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxZW50ZnFuY2lyZHV2aGhlcm5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5MTg1MzMsImV4cCI6MjA1MjQ5NDUzM30.O5lv175vHCRk1zXzWo9E8HmpKBIFHd8nOz1As0ZvxHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);